---
- name: set up mysql packages
  sudo: yes
  shell: wget -O /etc/yum.repos.d/mysql-community-release-el7-5.noarch.rpm http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm && rpm -ivh --replacepkgs /etc/yum.repos.d/mysql-community-release-el7-5.noarch.rpm

- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
   - mysql
   - mysql-devel
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=true
